# Generated by Django 3.1 on 2020-09-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='since',
            field=models.DateTimeField(help_text='Filter Tweets since date(Example: 2017-12-26 00:00:00).', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='until',
            field=models.DateTimeField(help_text='Filter Tweets sent until date(Example: 2017-12-27 00:00:00).', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scraper.job'),
        ),
    ]
