# Generated by Django 3.1 on 2020-09-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200913_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scraper.job'),
        ),
    ]
