# Generated by Django 3.1 on 2020-09-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
