# Generated by Django 3.1 on 2020-09-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
